image: registry.gitlab.com/rendaw/pyxyzygy-builenv

stages:
  - world

cache:
  paths:
    - /root/.m2

windows:
  stage: world
  script: ./build.py windows

linux:
  stage: world
  script: ./build.py linux
