image: registry.gitlab.com/rendaw/pyxyzygy-builenv

stages:
  - world

cache:
  paths:
    - .m2

linux:
  stage: world
  script: ./build.py linux ${CI_COMMIT_REF_NAME}
  only:
    - stable
    - experimental

windows:
  stage: world
  script: ./build.py windows ${CI_COMMIT_REF_NAME}
  only:
    - stable
    - experimental
