image: registry.gitlab.com/rendaw/pyxyzygy-builenv

variables:
  BUILD_LINUX_JAVA: /usr/lib/jvm/java-11-openjdk
  BUILD_WINDOWS_JAVA: /jdk-11.0.2
  BUILD_WINDOWS_CXX: x86_64-w64-mingw32-g++
  BUILD_WINDOWS_INCLUDE: /usr/x86_64-w64-mingw32/sys-root/mingw/include/c++
  BUILD_WINDOWS_LIB: /usr/x86_64-w64-mingw32/sys-root/mingw/lib

stages:
  - world

build:
  stage: world
  script:
    - sed -i -e "s#GEN_PATH#/jdk-11.0.2#" app/toolchains.xml
    - echo $BUILD_LINUX_JAVA
    - JAVA_HOME=$BUILD_LINUX_JAVA mvn clean package -X -e --global-toolchains app/toolchains.xml
